### ISSUE TITLE
Can't install PyCBC

### ISSUE THREAD

**Issue by prasia-p** [gw-odw/odw-2021#17]
! pip install -q 'PyCBC==1.18.0'' "lalsuite==6.82" shows the error:

ERROR: Could not find a version that satisfies the requirement PyCBC==1.18.0 lalsuite==6.82 (from versions: 0.1.2, 0.1.3, 0.1.4, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.3.6, 1.4.0, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.4, 1.10.1, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.8, 1.11.9, 1.11.11, 1.11.13, 1.11.14, 1.12.1, 1.12.2, 1.12.3, 1.12.4, 1.13.0, 1.13.1, 1.13.2, 1.13.3, 1.13.4, 1.13.5, 1.13.6, 1.13.7, 1.13.8, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 1.15.6, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.16.7, 1.16.8, 1.16.9, 1.16.10, 1.16.11, 1.16.12, 1.17.0, 1.17.1, 1.18.0, 1.18.1)
ERROR: No matching distribution found for PyCBC==1.18.0' 'lalsuite==6.82'

**Comment by martinberoiz** [comment]
Try using double quotes or no quotes at all:

    ! pip install -q PyCBC==1.10.2 lalsuite==6.82

or

    ! pip install -q "PyCBC==1.10.2" "lalsuite==6.82"

Even then, I think you may have set the wrong versions. There is no [version 1.10.2 for PyCBC](https://pypi.org/project/PyCBC/#history).

**Comment by prasia-p** [comment]
> Try using double quotes or no quotes at all:
> 
> ```
> ! pip install -q PyCBC==1.10.2 lalsuite==6.82
> ```
> 
> or
> 
> ```
> ! pip install -q "PyCBC==1.10.2" "lalsuite==6.82"
> ```
> 
> Even then, I think you may have set the wrong versions. There is no [version 1.10.2 for PyCBC](https://pypi.org/project/PyCBC/#history).

Yes. Same error for all versions. Unable to install lalsuite separately. The same error is being shown. Tried virtual environment as well.

**Comment by martinberoiz** [comment]
It could be because you are asking pip a version that doesn't exist. Which notebook are you working with?

**Comment by prasia-p** [comment]
I'm using Jypyter notebook and my OS is windows 10

**Comment by martinberoiz** [comment]
Oh, I see. I don't have much experience with Windows machines. What tutorial number are you working on?

For a quick fix, you may want to try running the notebooks in a Google Collab notebook or mybinder. 
See Options 1 and 2 here: https://github.com/gw-odw/odw-2021/blob/master/setup.md

**Comment by prasia-p** [comment]
I'm working on tutorial 1.4.. In Google Collab it's working though. In there it was suggested to work on notebook. Till now everything was working fine.

**Comment by jkanner** [comment]
Hi Martin and Prasia,

If you don't mind me jumping in, "Option 4" in the same instructions is specifically for Windows:
https://github.com/gw-odw/odw-2021/blob/master/setup.md

Co-lab and mybinder should also work well.

Good luck!

Best,
 jonah

**Comment by martinberoiz** [comment]
Hi Jonah, thanks for pointing that out.

@Prasia, I'm glad it works for you in collab. I'll go ahead and close this issue. If you need more assistance, you can open another issue or reserve office hours on this link: https://www.eventbrite.com/e/gwosc-office-hours-tickets-147886956869.
